name: KS Panel Testing

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
        b: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
      max-parallel: 1

    steps:
      - name: Restore database from Releases (if exists)
        run: |
          mkdir -p $HOME/.kspanel
          if gh release view latest-db >/dev/null 2>&1; then
            echo "Release found. Downloading database..."
            gh release download latest-db -p "database.zip" -D /tmp
            unzip -o /tmp/database.zip -d $HOME/.kspanel
          else
            echo "No previous database release found."
          fi

      - name: Download and install cloudflared
        run: |
          echo "Downloading cloudflared..."
          curl -L -o cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Install cloudflared service
        run: |
          sudo cloudflared service install eyJhIjoiZTJkZjY3MDI5ZWZlZTBmY2JhM2ExMjNjN2VmNTcxNTAiLCJ0IjoiMGQ2Yzk5YjQtMGUzZC00NzEyLWFmNDctNzM0MGU5YTEyOGE3IiwicyI6IlkyVTNOelV5WmpBdFl6SmpOeTAwTjJZMExUbGpNMk10T0dJelltRmtOREk1T1dOaCJ9

      - name: Prepare KS Panel
        run: |
          wget https://raw.githubusercontent.com/ks-app-518/ksanel-testing/refs/heads/main/kspanel
          KS_FILE="kspanel"
          chmod +x "$KS_FILE"
          sudo mv "$KS_FILE" /usr/local/bin/kspanel
          ls -lh /usr/local/bin/kspanel
          kspanel
          kspanel database
          kspanel install || true
          kspanel start

      - name: Install tmate
        run: |
          curl -L https://github.com/tmate-io/tmate/releases/download/2.4.0/tmate-2.4.0-static-linux-amd64.tar.xz -o tmate.tar.xz
          tar -xf tmate.tar.xz
          chmod +x tmate-2.4.0-static-linux-amd64/tmate
          sudo mv tmate-2.4.0-static-linux-amd64/tmate /usr/bin/tmate
          tmate -V

      - name: Start vps-runtime
        run: |
          TMATE_SOCK=/tmp/tmate.sock
          tmate -S $TMATE_SOCK new-session -d
          tmate -S $TMATE_SOCK wait tmate-ready

          echo "SSH connection:"
          tmate -S $TMATE_SOCK display -p "#{tmate_ssh}"

          echo "Web connection:"
          tmate -S $TMATE_SOCK display -p "#{tmate_web}"

          sleep 21300

      - name: Zip database
        if: always()
        run: |
          if [ -d "$HOME/.kspanel/database" ]; then
            cd $HOME/.kspanel
            zip -r database.zip database
            mv database.zip /tmp/database.zip
          else
            echo "Database folder not found"
            exit 0
          fi

      - name: Upload database to Releases
        run: |
          if: always()
          gh release delete latest-db -y || true
          gh release create latest-db /tmp/database.zip -t "Latest Database" -n "Auto saved KS Panel database"
